# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:

 # Container registry service connection established during pipeline creation
  dockerfilePath: '**/docker/catalogue-db/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'kubeinnovationacr132316be-auth'

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: microservicesdemo
      type: github
      name: northpoint/microservices-demo
      endpoint: github-svcconn
      ref: kevin-azure-pipelines

stages:
# - stage: DockerBuildPush
#   displayName: Docker Build & Push stage
#   jobs:  
#   - template: /pipeline-templates/docker-builddeploy-pipeline.yaml@microservicesdemo  # Template reference
#     parameters:
#       tag: $(tag)
#       acrRepo: catalogue-db
#       dockerfilePath: $(dockerfilePath)
- stage: HelmDeploy
  displayName: Helm Deploy
  jobs:

  - template: /pipeline-templates/helm-deploy-pipeline.yaml@microservicesdemo